name: Deploy
on:
  pull_request:

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v6
      - name: Create db secret
        run: echo "realaletrail" > db.secret
      - name: Create user secret
        run: echo "user" > user.secret
      - name: Create smtp secret
        run: echo "smtp" > smtp.secret
      - name: Build docker containers
        uses: hoverkraft-tech/compose-action@4894d2492015c1774ee5a13a95b1072093087ec3
        with:
          compose-file: "docker-compose.build.yml"
